package com.staffops.listener;

import com.staffops.StaffOpsPlugin;
import com.staffops.gui.StaffMenu;
import com.staffops.staff.StaffModeService;
import com.staffops.util.TimeUtil;
import io.papermc.paper.event.player.AsyncChatEvent;
import net.kyori.adventure.text.serializer.plain.PlainTextComponentSerializer;
import org.bukkit.*;
import org.bukkit.entity.Player;
import org.bukkit.event.*;
import org.bukkit.event.block.*;
import org.bukkit.event.entity.*;
import org.bukkit.event.inventory.*;
import org.bukkit.event.player.*;
import org.bukkit.inventory.EquipmentSlot;
import org.bukkit.inventory.ItemStack;

import java.util.*;

public final class CoreListener implements Listener {
    private final StaffOpsPlugin plugin; private final Random random=new Random();
    public CoreListener(StaffOpsPlugin plugin){this.plugin=plugin;}

    @EventHandler public void login(PlayerLoginEvent e){if(plugin.operations().maintenance()&&!e.getPlayer().hasPermission("staffops.operations.maintenance.bypass"))e.disallow(PlayerLoginEvent.Result.KICK_OTHER,plugin.messages().plainPlayer("operations.maintenance-kick"));}
    @EventHandler public void join(PlayerJoinEvent e){Player p=e.getPlayer();plugin.playerData().joined(p);plugin.vanish().handleJoin(p);plugin.activity().record(p,"JOIN","Joined "+p.getWorld().getName());plugin.cases().recordTargetActivity(p,"JOIN","Joined "+p.getWorld().getName());Bukkit.getScheduler().runTask(plugin,()->plugin.staffMode().recoverIfNeeded(p));}
    @EventHandler public void quit(PlayerQuitEvent e){plugin.playerData().quit(e.getPlayer());plugin.activity().record(e.getPlayer(),"QUIT","Disconnected");plugin.cases().recordTargetActivity(e.getPlayer(),"QUIT","Disconnected");plugin.investigation().stop(e.getPlayer());plugin.cases().endSession(e.getPlayer());}

    @EventHandler(priority=EventPriority.HIGHEST) public void menuClick(InventoryClickEvent e){if(e.getView().getTopInventory().getHolder() instanceof StaffMenu menu){e.setCancelled(true);if(e.getWhoClicked() instanceof Player)menu.click(e);return;}if(e.getWhoClicked() instanceof Player p&&(plugin.freeze().isFrozen(p.getUniqueId())||plugin.staffMode().isActive(p)))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST) public void menuDrag(InventoryDragEvent e){if(e.getView().getTopInventory().getHolder() instanceof StaffMenu){e.setCancelled(true);return;}if(e.getWhoClicked() instanceof Player p&&(plugin.freeze().isFrozen(p.getUniqueId())||plugin.staffMode().isActive(p)))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST) public void swap(PlayerSwapHandItemsEvent e){if(plugin.freeze().isFrozen(e.getPlayer().getUniqueId())||plugin.staffMode().isActive(e.getPlayer()))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void move(PlayerMoveEvent e){if(plugin.freeze().isFrozen(e.getPlayer().getUniqueId())&&e.hasChangedBlock())e.setTo(e.getFrom());}

    @EventHandler(priority=EventPriority.HIGHEST) public void interact(PlayerInteractEvent e){Player p=e.getPlayer();if(plugin.freeze().isFrozen(p.getUniqueId())){e.setCancelled(true);return;}if(!plugin.staffMode().isActive(p)||e.getHand()!=EquipmentSlot.HAND)return;String tool=plugin.staffMode().toolId(e.getItem());if(tool==null)return;e.setCancelled(true);switch(tool){case StaffModeService.TOOL_NAVIGATOR->randomTeleport(p);case StaffModeService.TOOL_REPORTS->plugin.gui().reports(p);case StaffModeService.TOOL_VANISH->{boolean on=plugin.vanish().toggle(p);p.sendMessage(plugin.messages().staff(on?"vanish.enabled":"vanish.disabled"));}case StaffModeService.TOOL_ACTIVITY->plugin.gui().onlinePlayers(p,0);case StaffModeService.TOOL_DASHBOARD->plugin.gui().dashboard(p);default->{}}}
    @EventHandler(priority=EventPriority.HIGHEST) public void interactEntity(PlayerInteractEntityEvent e){Player staff=e.getPlayer();if(!plugin.staffMode().isActive(staff)||!(e.getRightClicked() instanceof Player target))return;String tool=plugin.staffMode().toolId(staff.getInventory().getItemInMainHand());if(tool==null)return;switch(tool){case StaffModeService.TOOL_FREEZE->{e.setCancelled(true);plugin.toggleFreeze(staff,target);}case StaffModeService.TOOL_INSPECTOR->{e.setCancelled(true);plugin.gui().profile(staff,target.getUniqueId(),target.getName());}case StaffModeService.TOOL_INVENTORY->{e.setCancelled(true);plugin.gui().inspect(staff,target,false);}default->{}}}
    private void randomTeleport(Player staff){List<Player> targets=new ArrayList<>(Bukkit.getOnlinePlayers().stream().filter(p->!p.equals(staff)&&!p.hasPermission("staffops.vanish.see")).toList());if(targets.isEmpty()){staff.sendMessage(plugin.messages().staff("investigation.no-targets"));return;}Player target=targets.get(random.nextInt(targets.size()));plugin.investigation().teleport(staff,target);staff.sendMessage(plugin.messages().staff("investigation.random-teleport",Map.of("player",target.getName())));}

    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void command(PlayerCommandPreprocessEvent e){String storedCommand=plugin.activity().commandForStorage(e.getMessage());plugin.activity().record(e.getPlayer(),"COMMAND",storedCommand);plugin.cases().recordTargetActivity(e.getPlayer(),"COMMAND",storedCommand);if(!plugin.freeze().isFrozen(e.getPlayer().getUniqueId()))return;String c=e.getMessage().toLowerCase(Locale.ROOT);if(!(c.startsWith("/msg ")||c.startsWith("/tell ")||c.startsWith("/r ")||c.startsWith("/reply "))){e.setCancelled(true);e.getPlayer().sendMessage(plugin.messages().forAudience(e.getPlayer(),"freeze.command-blocked"));}}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void chat(AsyncChatEvent e){String text=PlainTextComponentSerializer.plainText().serialize(e.message());if(plugin.reports().hasDraft(e.getPlayer())){e.setCancelled(true);if(text.equalsIgnoreCase("cancel")){plugin.reports().cancelDraft(e.getPlayer());Bukkit.getScheduler().runTask(plugin,()->e.getPlayer().sendMessage(plugin.messages().forAudience(e.getPlayer(),"reports.draft-cancelled")));return;}int limit=plugin.getConfig().getInt("settings.reports.max-reason-length",160);if(text.length()>limit){Bukkit.getScheduler().runTask(plugin,()->e.getPlayer().sendMessage(plugin.messages().forAudience(e.getPlayer(),"reports.reason-too-long",Map.of("limit",String.valueOf(limit)))));return;}plugin.reports().completeDraft(e.getPlayer(),text).whenComplete((id,error)->Bukkit.getScheduler().runTask(plugin,()->{if(error==null)e.getPlayer().sendMessage(plugin.messages().forAudience(e.getPlayer(),"reports.draft-submitted"));else e.getPlayer().sendMessage(plugin.messages().forAudience(e.getPlayer(),"reports.failed"));}));return;}plugin.activity().record(e.getPlayer(),"CHAT",text);plugin.cases().recordTargetActivity(e.getPlayer(),"CHAT",text);plugin.punishments().activeMute(e.getPlayer().getUniqueId()).ifPresent(p->{e.setCancelled(true);long remaining=p.expiresAt()==null?0:p.expiresAt()-System.currentTimeMillis();Bukkit.getScheduler().runTask(plugin,()->e.getPlayer().sendMessage(plugin.messages().forAudience(e.getPlayer(),"punishments.muted-chat",Map.of("remaining",p.expiresAt()==null?" permanently":" for "+TimeUtil.compactDuration(remaining),"reason",p.reason()))));});}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void combat(EntityDamageByEntityEvent e){Player attacker=e.getDamager() instanceof Player p?p:null;Player victim=e.getEntity() instanceof Player p?p:null;if(attacker!=null&&victim!=null){String a="Attacked "+victim.getName()+" for "+String.format(Locale.US,"%.1f",e.getFinalDamage())+" damage",v="Hit by "+attacker.getName()+" for "+String.format(Locale.US,"%.1f",e.getFinalDamage())+" damage";plugin.activity().record(attacker,"COMBAT",a);plugin.activity().record(victim,"COMBAT",v);plugin.cases().recordTargetActivity(attacker,"COMBAT",a);plugin.cases().recordTargetActivity(victim,"COMBAT",v);}}
    @EventHandler(priority=EventPriority.MONITOR,ignoreCancelled=true) public void teleport(PlayerTeleportEvent e){String d=e.getCause()+" to "+e.getTo().getWorld().getName()+" "+e.getTo().getBlockX()+","+e.getTo().getBlockY()+","+e.getTo().getBlockZ();plugin.activity().record(e.getPlayer(),"TELEPORT",d);plugin.cases().recordTargetActivity(e.getPlayer(),"TELEPORT",d);}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void damage(EntityDamageEvent e){if(e.getEntity() instanceof Player p&&(plugin.freeze().isFrozen(p.getUniqueId())||plugin.staffMode().isActive(p)))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void place(BlockPlaceEvent e){if(plugin.freeze().isFrozen(e.getPlayer().getUniqueId())||plugin.staffMode().isActive(e.getPlayer()))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void breakBlock(BlockBreakEvent e){if(plugin.freeze().isFrozen(e.getPlayer().getUniqueId())||plugin.staffMode().isActive(e.getPlayer()))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void drop(PlayerDropItemEvent e){if(plugin.freeze().isFrozen(e.getPlayer().getUniqueId())||plugin.staffMode().isActive(e.getPlayer()))e.setCancelled(true);}
    @EventHandler(priority=EventPriority.HIGHEST,ignoreCancelled=true) public void pickup(EntityPickupItemEvent e){if(e.getEntity() instanceof Player p&&(plugin.freeze().isFrozen(p.getUniqueId())||plugin.staffMode().isActive(p)))e.setCancelled(true);}
    @EventHandler public void frozenQuit(PlayerQuitEvent e){if(!plugin.freeze().isFrozen(e.getPlayer().getUniqueId()))return;for(Player staff:Bukkit.getOnlinePlayers())if(staff.hasPermission("staffops.freeze"))staff.sendMessage(plugin.messages().staff("freeze.disconnected-alert",Map.of("player",e.getPlayer().getName())));plugin.audit().log(e.getPlayer(),"FROZEN_DISCONNECT",e.getPlayer().getUniqueId(),e.getPlayer().getName(),null);}
}
