package com.staffops.gui;

import com.staffops.StaffOpsPlugin;
import com.staffops.model.*;
import com.staffops.player.NoteService;
import com.staffops.report.ReportService;
import com.staffops.util.TimeUtil;
import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import net.kyori.adventure.text.format.TextDecoration;
import org.bukkit.*;
import org.bukkit.configuration.ConfigurationSection;
import org.bukkit.entity.Player;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.SkullMeta;

import java.util.*;
import java.util.concurrent.CompletableFuture;

public final class GuiService {
    private final StaffOpsPlugin plugin; private final MiniMessage mm=MiniMessage.miniMessage();
    public GuiService(StaffOpsPlugin plugin){this.plugin=plugin;}

    public void dashboard(Player staff){
        StaffMenu m=new StaffMenu(6,mm("<gradient:#27E6E6:#FF4FB8><bold>Staff Operations</bold></gradient>"));fill(m);
        setIf(m,10,staff,"staffops.inspect",item(Material.PLAYER_HEAD,"<aqua><bold>Player Management</bold>","<gray>Profiles, intelligence and actions"),e->onlinePlayers(staff,0));
        setIf(m,12,staff,"staffops.reports",item(Material.REPEATER,"<yellow><bold>Report Center</bold>","<gray>Prioritized live moderation queue"),e->reports(staff));
        setIf(m,14,staff,"staffops.cases",item(Material.WRITABLE_BOOK,"<gold><bold>Case Management</bold>","<gray>Investigations, evidence and timelines"),e->cases(staff));
        setIf(m,16,staff,"staffops.operations",item(Material.COMPARATOR,"<light_purple><bold>Operations Center</bold>","<gray>Server health, staff and security"),e->operations(staff));
        setIf(m,29,staff,"staffops.staffmode",item(Material.ENDER_EYE,"<aqua><bold>Staff Mode</bold>","<gray>Status: "+(plugin.staffMode().isActive(staff)?"<green>Enabled":"<red>Disabled"),"<gray>Click to toggle"),e->{boolean enabled=plugin.staffMode().toggle(staff);staff.sendMessage(plugin.messages().staff(enabled?"staffmode.enabled":"staffmode.disabled"));staff.closeInventory();});
        setIf(m,31,staff,"staffops.vanish",item(Material.LIME_DYE,"<aqua><bold>Vanish</bold>","<gray>Status: "+(plugin.vanish().isVanished(staff)?"<green>Hidden":"<red>Visible"),"<gray>Click to toggle"),e->{boolean enabled=plugin.vanish().toggle(staff);staff.sendMessage(plugin.messages().staff(enabled?"vanish.enabled":"vanish.disabled"));dashboard(staff);});
        m.set(49,item(Material.BARRIER,"<red>Close"),e->staff.closeInventory());staff.openInventory(m.getInventory());
    }

    public void onlinePlayers(Player staff,int page){
        if(!staff.hasPermission("staffops.inspect")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}
        List<Player> players=new ArrayList<>(Bukkit.getOnlinePlayers());players.sort(Comparator.comparing(Player::getName,String.CASE_INSENSITIVE_ORDER));StaffMenu m=new StaffMenu(6,mm("<aqua><bold>Player Management</bold> <dark_gray>• "+(page+1)));fill(m);int start=page*45;
        for(int i=0;i<45&&start+i<players.size();i++){Player p=players.get(start+i);m.set(i,head(p,"<white><bold>"+p.getName()+"</bold>","<gray>Ping: <white>"+p.getPing()+"ms","<gray>World: <white>"+p.getWorld().getName(),"<gray>Session: <white>"+durationSeconds(plugin.playerData().currentSessionSeconds(p.getUniqueId())),"","<yellow>Click to inspect"),e->profile(staff,p.getUniqueId(),p.getName()));}
        if(page>0)m.set(45,item(Material.ARROW,"<yellow>Previous Page"),e->onlinePlayers(staff,page-1));m.set(49,item(Material.BARRIER,"<red>Back"),e->dashboard(staff));if(start+45<players.size())m.set(53,item(Material.ARROW,"<yellow>Next Page"),e->onlinePlayers(staff,page+1));staff.openInventory(m.getInventory());
    }

    public void profile(Player staff,UUID targetId,String targetName){
        if(!staff.hasPermission("staffops.inspect")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}
        Player live=Bukkit.getPlayer(targetId);
        var pf=plugin.playerData().byUuid(targetId);var identity=plugin.playerData().identity(targetId,staff.hasPermission("staffops.profile.ip"));var punish=plugin.punishments().history(targetId,25);var notes=plugin.notes().list(targetId,10);var reports=plugin.reports().forPlayer(targetId,20);var cases=plugin.cases().forPlayer(targetId,10);
        CompletableFuture.allOf(pf,identity,punish,notes,reports,cases).whenComplete((v,err)->Bukkit.getScheduler().runTask(plugin,()->{
            if(!staff.isOnline())return;PlayerProfile p=pf.join().orElse(new PlayerProfile(targetId,targetName,0,0,0,0,null));IdentitySnapshot ids=identity.join();List<Punishment> ph=punish.join();List<NoteService.Note> ns=notes.join();List<ReportRecord> rs=reports.join();List<CaseRecord> cs=cases.join();Player online=Bukkit.getPlayer(targetId);
            StaffMenu m=new StaffMenu(6,mm("<aqua><bold>Player</bold> <dark_gray>• <white>"+safe(targetName)));fill(m);
            List<String> lore=new ArrayList<>();lore.add("<gray>UUID: <dark_gray>"+targetId);lore.add("<gray>Status: "+(online==null?"<red>Offline":"<green>Online"));lore.add("<gray>First joined: <white>"+dateOrUnknown(p.firstSeen()));lore.add("<gray>Last joined: <white>"+dateOrUnknown(p.lastJoin()));lore.add("<gray>Total tracked playtime: <white>"+durationSeconds(p.playtimeSeconds()));if(online!=null){lore.add("<gray>Online for: <white>"+durationSeconds(plugin.playerData().currentSessionSeconds(targetId)));lore.add("<gray>Server / world: <white>"+safe(plugin.getConfig().getString("settings.server-name","server"))+" <dark_gray>/ <white>"+safe(online.getWorld().getName()));lore.add("<gray>Location: <white>"+online.getLocation().getBlockX()+", "+online.getLocation().getBlockY()+", "+online.getLocation().getBlockZ());lore.add("<gray>Ping: <white>"+online.getPing()+"ms <dark_gray>| <gray>TPS: <white>"+String.format(Locale.US,"%.1f",Bukkit.getTPS()[0]));lore.add("<gray>Gamemode: <white>"+online.getGameMode());if(staff.hasPermission("staffops.profile.economy"))lore.add("<gray>Balance: <white>"+safe(plugin.integrations().balance(online)));if(staff.hasPermission("staffops.profile.permissions"))lore.add("<gray>Group: <white>"+safe(plugin.integrations().primaryGroup(online)));}
            lore.add("");lore.add("<gray>Punishments: <white>"+ph.size()+" <dark_gray>| <gray>Reports: <white>"+rs.size());lore.add("<gray>Notes: <white>"+ns.size()+" <dark_gray>| <gray>Cases: <white>"+cs.size());
            m.set(4,online!=null?head(online,"<white><bold>"+safe(targetName)+"</bold>",lore.toArray(String[]::new)):headOffline(targetId,targetName,"<white><bold>"+safe(targetName)+"</bold>",lore.toArray(String[]::new)),null);
            if(staff.hasPermission("staffops.profile.identity")){List<String> il=new ArrayList<>();il.add("<gray>Possible alt accounts: <white>"+ids.possibleAlts());il.add("<gray>Previous usernames: <white>"+Math.max(0,ids.previousNames().size()-1));il.add("<gray>IP history entries: <white>"+ids.ipHistory().size());il.add("");for(String name:ids.previousNames().stream().limit(5).toList())il.add("<dark_gray>• <gray>"+safe(name));if(staff.hasPermission("staffops.profile.ip")&&!ids.ipHistory().isEmpty()){il.add("");il.add("<gray>IP history:");for(String ip:ids.ipHistory().stream().limit(4).toList())il.add("<dark_gray>• <white>"+safe(ip));}m.set(10,item(Material.SPYGLASS,"<aqua><bold>Identity Intelligence</bold>",il.toArray(String[]::new)),null);}
            m.set(11,item(Material.PAPER,"<yellow><bold>Reports</bold>","<gray>Reports against player: <white>"+rs.size(),"<gray>Open the report center filtered mentally by player"),e->reports(staff));
            m.set(12,item(Material.NAME_TAG,"<gold><bold>Staff Notes</bold>",noteLore(ns)),null);
            m.set(13,item(Material.BOOK,"<red><bold>Punishment History</bold>",historyLore(ph)),null);
            m.set(14,item(Material.WRITABLE_BOOK,"<light_purple><bold>Cases</bold>",append(caseLore(cs),"","<yellow>Click to open player cases")),e->playerCases(staff,targetId,targetName));
            m.set(15,item(Material.CLOCK,"<aqua><bold>Recent Activity</bold>","<gray>Chat, commands and combat context","<yellow>Click to inspect"),e->activity(staff,targetId,targetName));
            if(online!=null && staff.hasPermission("staffops.profile.permissions")){List<String> perms=new ArrayList<>();perms.add("<gray>Primary group: <white>"+safe(plugin.integrations().primaryGroup(online)));perms.add("<gray>StaffOps permission nodes: <white>"+plugin.integrations().staffOpsPermissions(online).size());perms.add("");for(String node:plugin.integrations().staffOpsPermissions(online).stream().limit(7).toList())perms.add("<dark_gray>• <gray>"+safe(node));m.set(16,item(Material.NAME_TAG,"<aqua><bold>Permissions & Groups</bold>",perms.toArray(String[]::new)),null);}
            if(online!=null){
                action(m,19,staff,"staffops.freeze",Material.PACKED_ICE,"<red><bold>Freeze</bold>",e->{plugin.toggleFreeze(staff,online);profile(staff,targetId,targetName);});
                action(m,20,staff,"staffops.spectate",Material.ENDER_EYE,"<light_purple><bold>Spectate / POV</bold>",e->{plugin.investigation().spectate(staff,online);staff.closeInventory();});
                action(m,21,staff,"staffops.teleport",Material.ENDER_PEARL,"<aqua><bold>Teleport</bold>",e->{plugin.investigation().teleport(staff,online);staff.closeInventory();});
                action(m,22,staff,"staffops.follow",Material.COMPASS,"<yellow><bold>Follow Mode</bold>",e->{boolean on=plugin.investigation().toggleFollow(staff,online);staff.sendMessage(plugin.messages().staff(on?"investigation.follow-enabled":"investigation.follow-disabled",Map.of("player",online.getName())));staff.closeInventory();});
                action(m,28,staff,"staffops.inspect.inventory",Material.CHEST,"<yellow><bold>Inventory</bold>",e->inspect(staff,online,false));
                action(m,29,staff,"staffops.inspect.enderchest",Material.ENDER_CHEST,"<light_purple><bold>Ender Chest</bold>",e->inspect(staff,online,true));
            }
            action(m,24,staff,"staffops.punish.warn",Material.PAPER,"<yellow><bold>Warn</bold>",e->quickPunish(staff,targetId,targetName,PunishmentType.WARN,"Staff warning"));
            action(m,25,staff,"staffops.punish.mute",Material.FEATHER,"<gold><bold>Mute</bold>",e->punishMenu(staff,targetId,targetName));
            action(m,26,staff,"staffops.punish.kick",Material.IRON_BOOTS,"<red><bold>Kick</bold>",e->quickPunish(staff,targetId,targetName,PunishmentType.KICK,"Removed by staff"));
            action(m,27,staff,"staffops.punish.ban",Material.ANVIL,"<dark_red><bold>Ban / Punish</bold>",e->punishMenu(staff,targetId,targetName));
            action(m,31,staff,"staffops.cases.create",Material.MAP,"<gold><bold>Open Investigation Case</bold>",e->createCase(staff,targetId,targetName,"Manual staff investigation","NORMAL"));
            action(m,32,staff,"staffops.evidence",Material.KNOWLEDGE_BOOK,"<aqua><bold>Capture Evidence Snapshot</bold>",e->captureEvidence(staff,targetId,targetName));
            m.set(45,item(Material.ARROW,"<yellow>Back"),e->onlinePlayers(staff,0));m.set(49,item(Material.BARRIER,"<red>Close"),e->staff.closeInventory());staff.openInventory(m.getInventory());
        }));
    }

    public void activity(Player staff,UUID target,String name){if(!staff.hasPermission("staffops.profile.activity")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}StaffMenu m=new StaffMenu(6,mm("<aqua><bold>Recent Activity</bold> <dark_gray>• <white>"+safe(name)));fill(m);List<ActivityRecord> list=plugin.activity().recent(target,45);for(int i=0;i<list.size();i++){ActivityRecord a=list.get(i);Material mat=switch(a.type()){case "CHAT"->Material.WRITABLE_BOOK;case "COMMAND"->Material.COMMAND_BLOCK;case "COMBAT"->Material.IRON_SWORD;case "TELEPORT"->Material.ENDER_PEARL;default->Material.CLOCK;};m.set(i,item(mat,"<white><bold>"+safe(a.type())+"</bold>","<gray>"+safe(a.details()),"<dark_gray>"+TimeUtil.formatDate(a.createdAt())),null);}m.set(49,item(Material.ARROW,"<yellow>Back to Player"),e->profile(staff,target,name));staff.openInventory(m.getInventory());}

    public void inspect(Player staff,Player target,boolean ender){String perm=ender?"staffops.inspect.enderchest":"staffops.inspect.inventory";if(!staff.hasPermission(perm)){staff.sendMessage(plugin.messages().staff("no-permission"));return;}StaffMenu m=new StaffMenu(ender?3:6,mm((ender?"<light_purple><bold>Ender Chest":"<yellow><bold>Inventory")+"</bold> <dark_gray>• <white>"+safe(target.getName())));ItemStack[] contents=ender?target.getEnderChest().getContents():target.getInventory().getContents();for(int i=0;i<Math.min(contents.length,m.getInventory().getSize());i++)if(contents[i]!=null)m.set(i,contents[i].clone(),null);staff.openInventory(m.getInventory());plugin.cases().recordActive(staff,ender?"ENDER_CHEST_INSPECT":"INVENTORY_INSPECT",target.getName());}

    public void reportCategories(Player reporter,Player target){StaffMenu m=new StaffMenu(3,mm("<yellow><bold>Report</bold> <dark_gray>• <white>"+safe(target.getName())));fill(m);int[] slots={10,11,12,14,15,16};ReportService.Category[] categories=ReportService.Category.values();Material[] icons={Material.DIAMOND_SWORD,Material.WRITABLE_BOOK,Material.EMERALD,Material.DIAMOND_PICKAXE,Material.PLAYER_HEAD,Material.PAPER};for(int i=0;i<categories.length;i++){ReportService.Category c=categories[i];m.set(slots[i],item(icons[i],"<yellow><bold>"+safe(c.display())+"</bold>","<gray>Select this report category"),e->{plugin.reports().beginDraft(reporter,target,c);reporter.closeInventory();reporter.sendMessage(plugin.messages().forAudience(reporter,"reports.reason-prompt",Map.of("player",target.getName(),"category",c.display())));});}m.set(22,item(Material.BARRIER,"<red>Cancel"),e->reporter.closeInventory());reporter.openInventory(m.getInventory());}

    public void reports(Player staff){if(!staff.hasPermission("staffops.reports")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}plugin.reports().openReports().thenAccept(list->Bukkit.getScheduler().runTask(plugin,()->{if(!staff.isOnline())return;StaffMenu m=new StaffMenu(6,mm("<yellow><bold>Report & Investigation Center</bold>"));fill(m);for(int i=0;i<Math.min(45,list.size());i++){ReportRecord r=list.get(i);Material icon=switch(r.priority()){case "CRITICAL"->Material.REDSTONE_BLOCK;case "HIGH"->Material.ORANGE_CONCRETE;default->Material.YELLOW_CONCRETE;};m.set(i,item(icon,"<white><bold>"+safe(r.targetName())+"</bold> <dark_gray>• <yellow>"+safe(r.category()),"<gray>Priority: "+priorityColor(r.priority())+safe(r.priority()),"<gray>Reports combined: <white>"+r.duplicateCount(),"<gray>Reporter: <white>"+safe(r.reporterName()),"<gray>Reason: <white>"+safe(r.reason()),"<gray>Status: <white>"+safe(r.status()),"","<yellow>Click to manage"),e->reportDetail(staff,r));}m.set(49,item(Material.BARRIER,"<red>Back"),e->dashboard(staff));staff.openInventory(m.getInventory());}));}

    private void reportDetail(Player staff,ReportRecord r){StaffMenu m=new StaffMenu(5,mm("<yellow><bold>Report #"+r.id()+"</bold> <dark_gray>• <white>"+safe(r.targetName())));fill(m);m.set(4,item(Material.PLAYER_HEAD,"<white><bold>"+safe(r.targetName())+"</bold>","<gray>Category: <white>"+safe(r.category()),"<gray>Priority: "+priorityColor(r.priority())+safe(r.priority()),"<gray>Reason: <white>"+safe(r.reason()),"<gray>Duplicate reports: <white>"+r.duplicateCount()),e->profile(staff,r.target(),r.targetName()));action(m,19,staff,"staffops.reports.claim",Material.LIME_DYE,"<green><bold>Claim</bold>",e->{plugin.reports().claimGroup(staff,r);reports(staff);});action(m,20,staff,"staffops.reports.watch",Material.SPYGLASS,"<aqua><bold>Watch</bold>",e->{plugin.reports().watchGroup(staff,r);Player t=Bukkit.getPlayer(r.target());if(t!=null)plugin.investigation().spectate(staff,t);});action(m,21,staff,"staffops.reports.dismiss",Material.GRAY_DYE,"<gray><bold>Dismiss</bold>",e->{plugin.reports().dismissGroup(staff,r,"Dismissed by staff");reports(staff);});action(m,22,staff,"staffops.reports.escalate",Material.REDSTONE_BLOCK,"<red><bold>Escalate</bold>",e->{plugin.reports().escalateGroup(staff,r);reports(staff);});action(m,23,staff,"staffops.cases.create",Material.WRITABLE_BOOK,"<gold><bold>Open Case</bold>",e->createCase(staff,r.target(),r.targetName(),r.category()+": "+r.reason(),r.priority()));action(m,24,staff,"staffops.punish",Material.ANVIL,"<dark_red><bold>Punish</bold>",e->punishMenu(staff,r.target(),r.targetName()));m.set(40,item(Material.ARROW,"<yellow>Back"),e->reports(staff));staff.openInventory(m.getInventory());}

    public void cases(Player staff){if(!staff.hasPermission("staffops.cases")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}plugin.cases().openCases().thenAccept(list->Bukkit.getScheduler().runTask(plugin,()->{StaffMenu m=new StaffMenu(6,mm("<gold><bold>Case Management</bold>"));fill(m);for(int i=0;i<Math.min(45,list.size());i++){CaseRecord c=list.get(i);m.set(i,item(Material.WRITABLE_BOOK,"<gold><bold>CASE #"+c.id()+"</bold> <dark_gray>• <white>"+safe(c.targetName()),"<gray>Priority: "+priorityColor(c.priority())+safe(c.priority()),"<gray>Staff: <white>"+safe(c.openedByName()),"<gray>Reason: <white>"+safe(c.reason()),"<gray>Status: <green>"+safe(c.status()),"<dark_gray>Opened "+TimeUtil.formatDate(c.createdAt()),"","<yellow>Click to investigate"),e->caseDetail(staff,c));}m.set(49,item(Material.BARRIER,"<red>Back"),e->dashboard(staff));staff.openInventory(m.getInventory());}));}
    public void playerCases(Player staff,UUID target,String name){plugin.cases().forPlayer(target,45).thenAccept(list->Bukkit.getScheduler().runTask(plugin,()->{StaffMenu m=new StaffMenu(6,mm("<gold><bold>Cases</bold> <dark_gray>• <white>"+safe(name)));fill(m);for(int i=0;i<list.size();i++){CaseRecord c=list.get(i);m.set(i,item(Material.WRITABLE_BOOK,"<gold><bold>CASE #"+c.id()+"</bold>","<gray>Status: <white>"+safe(c.status()),"<gray>Reason: <white>"+safe(c.reason()),"<dark_gray>"+TimeUtil.formatDate(c.createdAt())),e->caseDetail(staff,c));}m.set(49,item(Material.ARROW,"<yellow>Back"),e->profile(staff,target,name));staff.openInventory(m.getInventory());}));}
    public void caseDetail(Player staff,CaseRecord c){plugin.cases().events(c.id(),25).thenAccept(events->Bukkit.getScheduler().runTask(plugin,()->{plugin.cases().activate(staff,c);StaffMenu m=new StaffMenu(6,mm("<gold><bold>CASE #"+c.id()+"</bold> <dark_gray>• <white>"+safe(c.targetName())));fill(m);m.set(4,item(Material.MAP,"<gold><bold>Investigation Case</bold>","<gray>Player: <white>"+safe(c.targetName()),"<gray>Staff: <white>"+safe(c.openedByName()),"<gray>Priority: "+priorityColor(c.priority())+safe(c.priority()),"<gray>Status: <white>"+safe(c.status()),"<gray>Reason: <white>"+safe(c.reason())),null);List<String> timeline=new ArrayList<>();for(CaseEvent ev:events.stream().limit(12).toList())timeline.add("<dark_gray>• <gray>"+TimeUtil.formatDate(ev.createdAt())+" <white>"+safe(ev.type())+": <gray>"+safe(ev.details()));m.set(13,item(Material.CLOCK,"<aqua><bold>Case Timeline</bold>",timeline.toArray(String[]::new)),null);action(m,19,staff,"staffops.inspect",Material.PLAYER_HEAD,"<aqua><bold>Player Profile</bold>",e->profile(staff,c.target(),c.targetName()));action(m,20,staff,"staffops.evidence",Material.KNOWLEDGE_BOOK,"<yellow><bold>Capture Evidence</bold>",e->captureEvidence(staff,c.target(),c.targetName()));Player target=Bukkit.getPlayer(c.target());if(target!=null){action(m,21,staff,"staffops.spectate",Material.ENDER_EYE,"<light_purple><bold>POV Mode</bold>",e->{plugin.investigation().spectate(staff,target);staff.closeInventory();});action(m,22,staff,"staffops.follow",Material.COMPASS,"<aqua><bold>Follow Mode</bold>",e->{plugin.investigation().toggleFollow(staff,target);staff.closeInventory();});action(m,23,staff,"staffops.freeze",Material.PACKED_ICE,"<red><bold>Freeze</bold>",e->{plugin.toggleFreeze(staff,target);caseDetail(staff,c);});}action(m,24,staff,"staffops.punish",Material.ANVIL,"<dark_red><bold>Punish</bold>",e->punishMenu(staff,c.target(),c.targetName()));action(m,31,staff,"staffops.cases.close",Material.LIME_DYE,"<green><bold>Close Case</bold>",e->{plugin.cases().close(staff,c.id(),"Resolved by staff");cases(staff);});m.set(49,item(Material.ARROW,"<yellow>Back"),e->cases(staff));staff.openInventory(m.getInventory());}));}

    private void createCase(Player staff,UUID target,String name,String reason,String priority){plugin.cases().create(staff,target,name,reason,priority).thenAccept(id->Bukkit.getScheduler().runTask(plugin,()->{staff.sendMessage(plugin.messages().staff("cases.created",Map.of("id",String.valueOf(id),"player",name)));plugin.evidence().capture(staff,target,name,id,"Automatic opening snapshot");plugin.cases().get(id).thenAccept(c->c.ifPresent(record->Bukkit.getScheduler().runTask(plugin,()->caseDetail(staff,record))));}));}
    private void captureEvidence(Player staff,UUID target,String name){Long caseId=plugin.cases().activeCase(staff);plugin.evidence().capture(staff,target,name,caseId,"Manual activity snapshot").thenAccept(id->Bukkit.getScheduler().runTask(plugin,()->{staff.sendMessage(plugin.messages().staff("evidence.captured",Map.of("id",String.valueOf(id),"player",name)));plugin.cases().recordActive(staff,"EVIDENCE_CAPTURED","Evidence #"+id+" for "+name);}));}

    public void evidence(Player staff,UUID target,String name){if(!staff.hasPermission("staffops.evidence")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}plugin.evidence().listForPlayer(target,45).thenAccept(list->Bukkit.getScheduler().runTask(plugin,()->{StaffMenu m=new StaffMenu(6,mm("<aqua><bold>Evidence</bold> <dark_gray>• <white>"+safe(name)));fill(m);for(int i=0;i<list.size();i++)m.set(i,item(Material.KNOWLEDGE_BOOK,"<yellow><bold>Evidence</bold>","<gray>"+safe(list.get(i))),null);m.set(45,item(Material.EMERALD,"<green><bold>Capture New Snapshot</bold>","<gray>Capture recent activity into durable evidence"),e->{captureEvidence(staff,target,name);evidence(staff,target,name);});m.set(49,item(Material.ARROW,"<yellow>Back"),e->profile(staff,target,name));staff.openInventory(m.getInventory());}));}

    public void operations(Player staff){if(!staff.hasPermission("staffops.operations")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}var s=plugin.operations().snapshot();plugin.database().latencyMillis().thenAccept(latency->Bukkit.getScheduler().runTask(plugin,()->{StaffMenu m=new StaffMenu(6,mm("<light_purple><bold>Server Operations Center</bold>"));fill(m);m.set(10,item(Material.REDSTONE_TORCH,"<aqua><bold>SERVER</bold>","<gray>TPS: <white>"+String.format(Locale.US,"%.2f",s.tps()),"<gray>MSPT: <white>"+String.format(Locale.US,"%.2f",s.mspt()),"<gray>Players: <white>"+s.players()+"/"+s.maxPlayers(),"<gray>Chunks: <white>"+s.chunks(),"<gray>Entities: <white>"+s.entities()),null);m.set(12,item(Material.CHEST,"<yellow><bold>MEMORY</bold>","<gray>Used: <white>"+mb(s.usedMemory())+" MB","<gray>Max: <white>"+mb(s.maxMemory())+" MB"),null);m.set(14,item(Material.HOPPER,"<green><bold>DATABASE</bold>","<gray>Status: <green>Connected","<gray>Latency: <white>"+latency+"ms","<gray>Pool: <white>"+plugin.database().activeConnections()+" active / "+plugin.database().totalConnections()+" total"),null);int staffCount=(int)Bukkit.getOnlinePlayers().stream().filter(p->p.hasPermission("staffops.use")).count();m.set(16,item(Material.PLAYER_HEAD,"<aqua><bold>STAFF</bold>","<gray>Online: <white>"+staffCount,"<gray>Vanish: <white>"+Bukkit.getOnlinePlayers().stream().filter(plugin.vanish()::isVanished).count()),null);long commandMinute=plugin.activity().countTypeSince("COMMAND",System.currentTimeMillis()-60_000L);m.set(22,item(Material.SHIELD,"<red><bold>SECURITY</bold>","<gray>Commands last 60s: <white>"+commandMinute,"<gray>Maintenance: "+(s.maintenance()?"<yellow>Enabled":"<green>Disabled"),"<gray>Whitelist: "+(s.whitelist()?"<yellow>Enabled":"<green>Disabled")),null);action(m,28,staff,"staffops.operations.maintenance",s.maintenance()?Material.REDSTONE_BLOCK:Material.LIME_CONCRETE,"<yellow><bold>Maintenance</bold>",e->{plugin.operations().setMaintenance(!plugin.operations().maintenance());staff.sendMessage(plugin.messages().staff(plugin.operations().maintenance()?"operations.maintenance-enabled":"operations.maintenance-disabled"));operations(staff);});action(m,30,staff,"staffops.operations.whitelist",Bukkit.hasWhitelist()?Material.IRON_DOOR:Material.OAK_DOOR,"<yellow><bold>Whitelist</bold>",e->{Bukkit.setWhitelist(!Bukkit.hasWhitelist());plugin.audit().log(staff,"WHITELIST_TOGGLE",null,null,"enabled="+Bukkit.hasWhitelist());operations(staff);});action(m,32,staff,"staffops.operations.restart",Material.REDSTONE_BLOCK,"<red><bold>Restart Server</bold>",e->restartConfirmation(staff));m.set(49,item(Material.ARROW,"<yellow>Back"),e->dashboard(staff));staff.openInventory(m.getInventory());}));}

    private void restartConfirmation(Player staff){StaffMenu m=new StaffMenu(3,mm("<red><bold>Confirm Server Restart</bold>"));fill(m);m.set(11,item(Material.LIME_CONCRETE,"<green><bold>Cancel</bold>","<gray>Return without restarting"),e->operations(staff));m.set(15,item(Material.REDSTONE_BLOCK,"<red><bold>CONFIRM RESTART</bold>","<red>This restarts the entire server.","<gray>Use only when you are ready."),e->{plugin.audit().log(staff,"SERVER_RESTART",null,null,"Confirmed from Operations Center");Bukkit.broadcast(plugin.messages().player("operations.restart-warning"));Bukkit.getScheduler().runTaskLater(plugin,()->Bukkit.getServer().restart(),60L);staff.closeInventory();});staff.openInventory(m.getInventory());}

    public void punishMenu(Player staff,UUID target,String name){if(!staff.hasPermission("staffops.punish")){staff.sendMessage(plugin.messages().staff("no-permission"));return;}ConfigurationSection root=plugin.getConfig().getConfigurationSection("punishment-ladders");StaffMenu m=new StaffMenu(5,mm("<red><bold>Punish</bold> <dark_gray>• <white>"+safe(name)));fill(m);if(root!=null){int slot=10;for(String ladder:root.getKeys(false)){ConfigurationSection sec=root.getConfigurationSection(ladder);if(sec==null)continue;Material mat=Material.matchMaterial(sec.getString("icon","PAPER"));if(mat==null)mat=Material.PAPER;String display=sec.getString("display",ladder);String ladderId=ladder;m.set(slot++,item(mat,"<yellow><bold>"+safe(display)+"</bold>","<gray>Apply the next configured escalation step","<yellow>Click to continue"),e->applyLadder(staff,target,name,ladderId,sec));if(slot%9==8)slot+=2;}}m.set(40,item(Material.ARROW,"<yellow>Back"),e->profile(staff,target,name));staff.openInventory(m.getInventory());}
    private void applyLadder(Player staff,UUID target,String name,String ladder,ConfigurationSection sec){plugin.punishments().ladderCount(target,ladder).thenAccept(count->Bukkit.getScheduler().runTask(plugin,()->{List<Map<?,?>> steps=sec.getMapList("steps");if(steps.isEmpty()){staff.sendMessage(plugin.messages().staff("punishments.invalid-ladder"));return;}Map<?,?> step=steps.get(Math.min(count,steps.size()-1));PunishmentType type=PunishmentType.valueOf(String.valueOf(step.get("type")).toUpperCase(Locale.ROOT));long duration=TimeUtil.parseDurationMillis(String.valueOf(step.get("duration")));String reason=String.valueOf(step.get("reason"));plugin.punishments().apply(staff,target,name,type,reason,duration,ladder).whenComplete((p,err)->Bukkit.getScheduler().runTask(plugin,()->{if(err!=null){staff.sendMessage(plugin.messages().staff("punishments.failed",Map.of("error",rootMessage(err))));return;}staff.sendMessage(plugin.messages().staff("punishments.applied",Map.of("type",type.name(),"player",name)));plugin.cases().recordActive(staff,"PUNISHMENT",""+type+" -> "+name+" | "+reason);staff.closeInventory();}));}));}
    private void quickPunish(Player staff,UUID target,String name,PunishmentType type,String reason){plugin.punishments().apply(staff,target,name,type,reason,0,"manual").whenComplete((p,err)->Bukkit.getScheduler().runTask(plugin,()->{if(err!=null)staff.sendMessage(plugin.messages().staff("punishments.failed",Map.of("error",rootMessage(err))));else{staff.sendMessage(plugin.messages().staff("punishments.applied",Map.of("type",type.name(),"player",name)));plugin.cases().recordActive(staff,"PUNISHMENT",type+" -> "+name+" | "+reason);staff.closeInventory();}}));}

    private void action(StaffMenu m,int slot,Player staff,String permission,Material material,String name,java.util.function.Consumer<org.bukkit.event.inventory.InventoryClickEvent> action){if(staff.hasPermission(permission))m.set(slot,item(material,name,"<gray>Click to use"),action);else m.set(slot,item(Material.GRAY_DYE,"<dark_gray><bold>Locked</bold>","<gray>Missing permission: <dark_gray>"+permission),null);}
    private void setIf(StaffMenu m,int slot,Player staff,String perm,ItemStack item,java.util.function.Consumer<org.bukkit.event.inventory.InventoryClickEvent> action){if(staff.hasPermission(perm))m.set(slot,item,action);}
    private void fill(StaffMenu m){ItemStack pane=item(Material.GRAY_STAINED_GLASS_PANE," ");for(int i=0;i<m.getInventory().getSize();i++)m.getInventory().setItem(i,pane);}
    private ItemStack item(Material mat,String name,String... lore){ItemStack i=new ItemStack(mat);i.editMeta(meta->{meta.displayName(mm(name));if(lore.length>0)meta.lore(Arrays.stream(lore).map(this::mm).toList());});return i;}
    private ItemStack head(Player p,String name,String... lore){ItemStack i=item(Material.PLAYER_HEAD,name,lore);if(i.getItemMeta() instanceof SkullMeta sm){sm.setOwningPlayer(p);i.setItemMeta(sm);}return i;}
    private ItemStack headOffline(UUID id,String playerName,String name,String... lore){ItemStack i=item(Material.PLAYER_HEAD,name,lore);if(i.getItemMeta() instanceof SkullMeta sm){sm.setOwningPlayer(Bukkit.getOfflinePlayer(id));i.setItemMeta(sm);}return i;}
    private Component mm(String text){return mm.deserialize(text).decoration(TextDecoration.ITALIC,false);}
    private String[] historyLore(List<Punishment> list){if(list.isEmpty())return new String[]{"<gray>No punishment history."};List<String> out=new ArrayList<>();for(Punishment p:list.stream().limit(8).toList())out.add("<dark_gray>• <red>"+p.type()+" <gray>"+safe(p.reason())+" <dark_gray>"+TimeUtil.formatDate(p.createdAt()));return out.toArray(String[]::new);}
    private String[] noteLore(List<NoteService.Note> list){if(list.isEmpty())return new String[]{"<gray>No staff notes.","<dark_gray>Use /so note <player> <note>"};List<String> out=new ArrayList<>();for(NoteService.Note n:list.stream().limit(6).toList())out.add("<dark_gray>• <white>"+safe(n.staff())+": <gray>"+safe(n.text()));return out.toArray(String[]::new);}
    private String[] caseLore(List<CaseRecord> list){if(list.isEmpty())return new String[]{"<gray>No cases on record."};List<String> out=new ArrayList<>();for(CaseRecord c:list.stream().limit(5).toList())out.add("<dark_gray>• <gold>#"+c.id()+" <gray>"+safe(c.status())+" - "+safe(c.reason()));return out.toArray(String[]::new);}
    private String[] append(String[] base,String... extra){String[] out=Arrays.copyOf(base,base.length+extra.length);System.arraycopy(extra,0,out,base.length,extra.length);return out;}
    private String priorityColor(String p){return switch(p){case "CRITICAL"->"<red>";case "HIGH"->"<gold>";default->"<yellow>";};}
    private String dateOrUnknown(long millis){return millis<=0?"Unknown":TimeUtil.formatDate(millis);}private String durationSeconds(long sec){if(sec<=0)return "0m";return TimeUtil.compactDuration(sec*1000L);}private long mb(long bytes){return bytes/1024/1024;}private String safe(String s){return s==null?"":s.replace("<","&lt;").replace(">","&gt;");}
    private String rootMessage(Throwable t){Throwable c=t;while(c.getCause()!=null)c=c.getCause();return c.getMessage()==null?"Unknown error":c.getMessage();}
}
